services:
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - twitter-redis

volumes:
  redis-data:

networks:
  twitter-redis:
